### ISSUE TITLE
keys for testing response code 402 and 403

### ISSUE THREAD

**Issue by freyfogle** [ropensci/opencage#63] opened 2019-01-05 20:36 UTC
Hi everyone, 

just FYI I just added a bit to [the OpenCage library writing guidelines](https://github.com/OpenCageData/opencagedata-misc-docs/blob/master/library-guidelines.md)

We now have two keys you can use that will, respectively, always generate a 402 and 403 response if you want to create tests for that. 

I hope that is helpful. 

How can we get version 0.2.0 out? How can I help (short of learning R and actually submitting PRs). My offer stands to pay/donate to a charity of your choosing.

All good wishes for a great 2019, everyone.

**Comment by dpprdan** [comment] 2019-01-08 15:22
Thanks Ed, I already saw your [Ruby post](https://blog.opencagedata.com/post/new-year-new-ruby-library) and implemented the new keys in our tests [here](https://github.com/dpprdan/opencage/commit/ec344bedb516a269e4a0059478a77e1509e601f3). I'll leave this open for the time being, because the change is not merged into the main `master` branch, yet.  

But talking about tests: I get inconsistent responses for the following query, depending on which number I pass on to the `limit` parameter:
`https://api.opencagedata.com/geocode/v1/json?q=Berlin&bounds=-90.1%2C37.5%2C-68.9%2C46.7&limit=4&key=<<my_key>>`

With `limit` set to 1, 2, or 3, I get no result (i.e. the `results` field is empty), with `limit` set to a number `n` between 4 and 14, the number of results (`total_results` field) is consistently `n - 3`. So I get e.g. one result for `limit=4` and 11 results (apparently the maximum number of results) for `limit=14`. 

I see the same pattern if I use `countrycode=us` instead of the `bounds` parameter, i.e. with 
`https://api.opencagedata.com/geocode/v1/json?q=Berlin&countrycode=us&limit=3&key=<<my_key>>`.

Getting no results with `limit` set to 1, 2 or 3 is particularly problematic (since there obviously is data available), and I am pretty sure that this used to work, because we had `limit` set to 1 (and later to 3) in one of our tests.

Without the `bounds` parameter, i.e.
`https://api.opencagedata.com/geocode/v1/json?q=Berlin&limit=1&key=<<my_key>>`, 
I get 1 result for `limit=1` and 2 results for `limit=2`, as expected, but again always `n - 1` results with `limit=n`, with `n` set to 3 or more.

This is not as bad as the "no results" above, but it is still problematic, because it suggests that there are fewer results available than specified by `limit` >= 3, while in reality there are more results available. 

Finally, regarding the `proximity` parameter, your [documentation](https://opencagedata.com/api#forward-opt) says: "Please note though, this is just one of many factors in the internal scoring we use for ranking results." Is the `limit` parameter one of these factors?
Because when I try to find Berlin in Massachusetts with 
`https://api.opencagedata.com/geocode/v1/json?q=Berlin&proximity=42.3%2C-71.1&limit=1&key=<<my_key>>` (the `proximity` coordinates are supposed to be near Boston, Massachusetts) and `limit` is set to 1 or 2 I only get Berlin, Germany. Only with `limit` set to 3 or more, the first result is Berlin, Massachusetts. If this is indeed not a bug, what is the rationale behind having the ranking depend on the `limit` parameter?

**Comment by freyfogle** [comment] 2019-01-08 15:24
Hallo Daniel,

frohes neues Jahr! Great to read that you are following our blog. 

We will have a look at this, thanks for the excellent examples. It sounds like a bug `limit` should not be changing the results. 

more soon,
Ed

**Comment by freyfogle** [comment] 2019-01-08 17:22
Thanks again for reporting this issue with `limit`.  A fix just went live. 

The core problem is an issue inside nominatim, we will work to fix that as well.

Please let me know how I can help get the new R module out. 

happy geocoding und alles Gute in 2019
Ed

**Comment by dpprdan** [comment] 2019-01-08 19:42
Thanks Ed!

I checked again and it seems only partially fixed. But maybe we have to wait for the issue to be fixed in Nominatim? Anyway,
`https://api.opencagedata.com/geocode/v1/json?q=Berlin&bounds=-90.1%2C37.5%2C-68.9%2C46.7&limit=4&key=<<my_key>>` 
seems to be fixed for `limit`s set to 1 through 7, but with limit set to 8 through 10 I get 7 results and to 11 through 13 I get n - 3 results. `limit=40` still gives me 10 results, but `limit=50` returns 11 results, the last one being "Berlien, IN". Again, I get a similar pattern for `countrycode=us` (but 8 results with `limit=12`, 12 results with `limit=16`, 20 results with `limit=24` and above). 

`https://api.opencagedata.com/geocode/v1/json?q=Berlin&limit=1&key=<<my_key>>` is fixed for `limit` set to 1 through 9, but returns n-1 results for `limit` 10 through (presumably) 49.

My `proximity` example seems to work as expected now, i.e. the ranking of results is not influenced by `limit` anymore. Could you share a bit more about the "just one of many factors"? Is there e.g. a distance threshold? (Berlin, NH is ranked fourth, behind two Berlin, Germany entries). 

Dir auch alles Gute in 2019!

**Comment by freyfogle** [comment] 2019-01-09 10:56
Hi, 

re: proximity - it is very hard to comment in detail because basically we are passing on the proximity hint to all the various geocoders we query behind the scenes. Meanwhile that list [has become pretty long](https://opencagedata.com/credits). Each one then does it's own thing which can depend on the exact query, there is not one unique algorithm. So really the only thing we can say is "it depends".

We'll look again at this `limit` issue. That said, be aware this is not a heavily used feature. Having just scanned through recent logs, the common use case is `limit=1` to get only a single result. No one is ever doing `limit=24`, though of course it should be theoretically possible. 

more soon,
Ed

**Comment by dpprdan** [comment] 2019-05-08 21:30
fixed in devel

**Closed as completed by dpprdan** 2019-05-08 21:30 UTC
